services:
  postgres:
    image: "postgres:10.5-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /pgdata
    healthcheck:
      test: pg_isready -d 'postgresql://postgres:postgres@postgres:5432/postgres'
    volumes:
      - ${PWD}/pgdata:/pgdata
  init-db:
    image: "webdevops/liquibase:postgres"
    command: "liquibase update"
    environment:
      LIQUIBASE_URL: jdbc:postgresql://postgres:5432/postgres
      LIQUIBASE_USERNAME: postgres
      LIQUIBASE_PASSWORD: postgres
    volumes:
      - ${PWD}/liquibase:/liquibase
    depends_on:
      postgres:
        condition: service_healthy
  hello:
    image: "hello-world"
    depends_on:
      init-db:
        condition: service_completed_successfully
