services:
  postgres:
    image: "postgres:10.5-alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /pgdata
    healthcheck:
      test: pg_isready -d 'postgresql://postgres:postgres@postgres:5432/postgres'
    volumes:
      - ${PWD}/pgdata:/pgdata
  init-db:
    image: "liquibase/liquibase:latest"
    command: "/changelog/entrypoint.sh"
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/postgres
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: postgres
    volumes:
      - ${PWD}/changelog:/changelog
    depends_on:
      postgres:
        condition: service_healthy
  hello:
    image: "hello-world"
    depends_on:
      init-db:
        condition: service_completed_successfully
